/* eslint-disable react/no-unescaped-entities */
import Head from "next/head";
// import Image from 'next/image'
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Money and Other Things</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className={styles["top-text"]}>SOMETHING'S COMING</h1>

      <h4 className={styles["bottom-text"]}>MONEYANDOTHERTHINGS.COM</h4>
    </div>
  );
}
