/* eslint-disable react/no-unescaped-entities */
import Head from "next/head";
import styles from "../styles/Home.module.css";

import Animation from "../components/Animation";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Money and Other Things</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        {/* <link rel="icon" href="/money-and-other-things.png" /> */}
      </Head>

      <div className={styles.main_content}>
        <div className={`${styles.top_text_container} ${styles.center}`}>
          <h1 className={styles.top_text}>SOMETHING'S COMING</h1>
        </div>

        <div className={styles.animation_container}>
          <Animation />
        </div>

        <div className={`${styles.bottom_text_container} ${styles.center}`}>
          <h4 className={styles.bottom_text}>MONEYANDOTHERTHINGS.COM</h4>
        </div>
      </div>
    </div>
  );
}
